'use client';
/* eslint-disable @next/next/no-img-element -- il percorso relativo deve funzionare anche sotto GitHub Pages */
import {useEffect,useMemo,useRef,useState} from 'react';
type R='pending'|'won'|'lost'|'void';
type Pick={id:string;match:string;market:string;odd:number;probability:number;confidence:number;result:R};
type Slip={id:string;season:string;matchday:number;date:string;stake:3;result:R;returnAmount:number;notes?:string;picks:Pick[]};
const EXAMPLE=`{\n  "season": "2026/27",\n  "matchday": 1,\n  "date": "2026-08-23",\n  "notes": "Prima giornata",\n  "selections": [\n    {\n      "match": "Inter - Torino",\n      "market": "1",\n      "odd": 1.55,\n      "probability": 70,\n      "confidence": 4\n    }\n  ]\n}`;
const labels:Record<R,string>={pending:'In attesa',won:'Vinta',lost:'Persa',void:'Nulla'};
const symbols:Record<R,string>={pending:'—',won:'✓',lost:'×',void:'○'};
const euro=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
const pct=(n:number)=>`${n.toFixed(1).replace('.',',')}%`;
function db(){return new Promise<IDBDatabase>((ok,no)=>{const q=indexedDB.open('seriea-multipla',1);q.onupgradeneeded=()=>q.result.createObjectStore('slips',{keyPath:'id'});q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function readAll(){const d=await db();return new Promise<Slip[]>((ok,no)=>{const q=d.transaction('slips').objectStore('slips').getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function put(s:Slip){const d=await db();return new Promise<void>((ok,no)=>{const q=d.transaction('slips','readwrite').objectStore('slips').put(s);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)})}
async function remove(id:string){const d=await db();return new Promise<void>((ok,no)=>{const q=d.transaction('slips','readwrite').objectStore('slips').delete(id);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)})}
async function replace(items:Slip[]){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('slips','readwrite'),s=t.objectStore('slips');s.clear();items.forEach(x=>s.put(x));t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
function parse(raw:unknown):Slip{if(!raw||typeof raw!=='object')throw Error('Il JSON deve contenere un oggetto.');const x=raw as Record<string,unknown>,a=x.selections;if(!Array.isArray(a)||a.length<1||a.length>6)throw Error('Servono da 1 a 6 selezioni.');const season=String(x.season||''),date=String(x.date||''),matchday=Number(x.matchday);if(!season||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isInteger(matchday)||matchday<1)throw Error('Controlla stagione, giornata e data.');const picks=a.map((v,i)=>{const z=v as Record<string,unknown>,odd=Number(z.odd),probability=Number(z.probability),confidence=Number(z.confidence);if(!z.match||!z.market||odd<=1||probability<=0||probability>100||confidence<1||confidence>5)throw Error(`Selezione ${i+1}: valori non validi.`);return{id:crypto.randomUUID(),match:String(z.match),market:String(z.market),odd,probability,confidence,result:'pending' as R}});return{id:`${season}-${matchday}-${date}`,season,matchday,date,stake:3,result:'pending',returnAmount:0,notes:String(x.notes||''),picks}}
export default function Home(){
 const[slips,setSlips]=useState<Slip[]>([]),[ready,setReady]=useState(false),[view,setView]=useState<'dash'|'history'|'detail'>('dash'),[chosen,setChosen]=useState(''),[modal,setModal]=useState<'import'|'schema'|'backup'|null>(null),[text,setText]=useState(''),[msg,setMsg]=useState('');const file=useRef<HTMLInputElement>(null);
 const load=async()=>{setSlips((await readAll()).sort((a,b)=>b.date.localeCompare(a.date)||b.matchday-a.matchday));setReady(true)};useEffect(()=>{readAll().then(data=>{setSlips(data.sort((a,b)=>b.date.localeCompare(a.date)||b.matchday-a.matchday));setReady(true)});const saved=localStorage.getItem('la-multipla-theme');if(saved==='light'||saved==='dark')document.documentElement.dataset.theme=saved;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')},[]);
 const selected=slips.find(x=>x.id===chosen)||slips[0];const stats=useMemo(()=>{const settled=slips.filter(s=>s.result!=='pending'),decisive=settled.filter(s=>s.result==='won'||s.result==='lost'),pending=slips.filter(s=>s.result==='pending'),settledStake=settled.length*3,returns=settled.reduce((a,s)=>a+s.returnAmount,0),profit=returns-settledStake,picks=slips.flatMap(s=>s.picks),settledPicks=picks.filter(x=>x.result==='won'||x.result==='lost'),wonPicks=settledPicks.filter(x=>x.result==='won').length,wonCount=decisive.filter(s=>s.result==='won').length,lostCount=decisive.filter(s=>s.result==='lost').length,odds=slips.map(s=>s.picks.reduce((a,p)=>a*p.odd,1)),values=picks.map(p=>(p.odd*p.probability/100-1)*100),chronological=settled.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.matchday-b.matchday),trend=chronological.map((s,i)=>({day:s.matchday,value:chronological.slice(0,i+1).reduce((a,x)=>a+x.returnAmount-3,0),result:s.result})),recent=settled.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.matchday-a.matchday),streakResult=recent[0]?.result,firstDifferent=recent.findIndex(s=>s.result!==streakResult),streak=streakResult==='won'||streakResult==='lost'?(firstDifferent===-1?recent.length:firstDifferent):0;return{stake:slips.length*3,settledStake,atRisk:pending.length*3,returns,profit,roi:settledStake?profit/settledStake*100:0,win:decisive.length?wonCount/decisive.length*100:0,hit:settledPicks.length?wonPicks/settledPicks.length*100:0,played:settled.length,pending:pending.length,wonCount,lostCount,wonPicks,lostPicks:settledPicks.length-wonPicks,totalPicks:picks.length,avgOdd:odds.length?odds.reduce((a,n)=>a+n,0)/odds.length:0,avgPicks:slips.length?picks.length/slips.length:0,avgValue:values.length?values.reduce((a,n)=>a+n,0)/values.length:0,best:chronological.length?Math.max(...chronological.map(s=>s.returnAmount-3)):0,worst:chronological.length?Math.min(...chronological.map(s=>s.returnAmount-3)):0,trend,streak,streakResult}},[slips]);
 const save=async(s:Slip)=>{await put(s);await load()};const importSlip=async()=>{try{const s=parse(JSON.parse(text));await put(s);setText('');setModal(null);setMsg(`Giornata ${s.matchday} importata.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'JSON non valido.')}};
 const backup=()=>{const b=new Blob([JSON.stringify({app:'seriea-multipla',version:1,exportedAt:new Date().toISOString(),slips},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`seriea-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 const deleteSlip=async(s:Slip)=>{if(!confirm(`Eliminare definitivamente la giornata ${s.matchday}?`))return;await remove(s.id);await load();setView('history');setMsg(`Giornata ${s.matchday} eliminata.`)};
 const restore=async(f:File)=>{try{const x=JSON.parse(await f.text());if(x.app!=='seriea-multipla'||!Array.isArray(x.slips))throw Error('Backup non riconosciuto.');await replace(x.slips);await load();setMsg('Backup ripristinato.')}catch(e){setMsg(e instanceof Error?e.message:'Backup non valido.')}};
 const toggleTheme=()=>{const root=document.documentElement,current=root.dataset.theme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'),next=current==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('la-multipla-theme',next)};
 const cycle=async(s:Slip,id:string)=>{const o:R[]=['pending','won','lost','void'];await save({...s,picks:s.picks.map(p=>p.id===id?{...p,result:o[(o.indexOf(p.result)+1)%4]}:p)})};const settle=async(s:Slip,r:R)=>{const odd=s.picks.reduce((a,p)=>a*p.odd,1);await save({...s,result:r,returnAmount:r==='won'?+(s.stake*odd).toFixed(2):r==='void'?3:0})};
 return <main className="shell"><header><div className="brand"><img src="./icon-192.png" alt=""/><span><strong>La Multipla</strong><small>Serie A · stake fisso €3</small></span></div><div className="header-actions"><button className="round theme-toggle" onClick={toggleTheme} aria-label="Cambia modalità colore"><span className="moon">☾</span><span className="sun">☀</span></button><button className="round" onClick={()=>setModal('backup')} aria-label="Backup">↥</button></div></header><section className="content">
 {view==='dash'&&<><div className="eye">PANORAMICA STAGIONE</div><h1>Il tuo campionato,<br/><em>una multipla alla volta.</em></h1>{!ready?<div className="empty">Caricamento…</div>:!slips.length?<div className="welcome"><div>⚽</div><h2>Pronto per la prima giornata?</h2><p>Importa il JSON della schedina. I dati restano solo su questo dispositivo.</p><button className="primary" onClick={()=>setModal('import')}>Importa schedina</button><button className="link" onClick={()=>setModal('schema')}>Vedi formato JSON</button></div>:<><div className="hero"><div className="hero-top"><small>PROFITTO REALIZZATO</small><span>{stats.played} concluse · {stats.pending} aperte</span></div><strong className={stats.profit>=0?'pos':'neg'}>{stats.profit>=0?'+':''}{euro(stats.profit)}</strong><div>{[['ROI',pct(stats.roi)],['Ritorni',euro(stats.returns)],['A rischio',euro(stats.atRisk)]].map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}</div></div><div className="metrics four"><span><small>Totale puntato</small><strong>{euro(stats.stake)}</strong></span><span><small>Quota media</small><strong>{stats.avgOdd.toFixed(2)}</strong></span><span><small>Media selezioni</small><strong>{stats.avgPicks.toFixed(1)}</strong></span><span><small>Value medio</small><strong className={stats.avgValue>=0?'pos-text':'neg-text'}>{stats.avgValue>=0?'+':''}{pct(stats.avgValue)}</strong></span></div><Title title="Curva del profitto" meta={slips[0]?.season}/><TrendChart points={stats.trend}/><div className="chart-caption"><span>Profitto cumulativo</span><small>Solo giornate concluse</small></div><Title title="Giornata per giornata" meta={`${stats.played}/38 concluse`}/><OutcomeChart slips={slips}/><div className="rings"><Ring value={stats.win} label="Multiple" detail={`${stats.wonCount} vinte · ${stats.lostCount} perse`}/><Ring value={stats.hit} label="Selezioni" detail={`${stats.wonPicks}/${stats.wonPicks+stats.lostPicks} corrette`}/></div><div className="season-card"><div className="season-head"><span><small>AVANZAMENTO STAGIONE</small><strong>{slips.length} di 38 giornate</strong></span><b>{pct(slips.length/38*100)}</b></div><div className="progress"><i style={{width:`${Math.min(100,slips.length/38*100)}%`}}/></div><div className="season-facts"><span><small>Esposizione prevista</small><b>{euro(114)}</b></span><span><small>Miglior giornata</small><b className="pos-text">{stats.played?`+${euro(Math.max(0,stats.best))}`:'—'}</b></span><span><small>Peggior giornata</small><b className="neg-text">{stats.played?euro(stats.worst):'—'}</b></span><span><small>Serie attuale</small><b>{stats.streak?`${stats.streak} ${stats.streakResult==='won'?'vinte':'perse'}`:'—'}</b></span></div></div><Title title="Ultima schedina" action={()=>{setChosen(slips[0].id);setView('detail')}}/><SlipCard slip={slips[0]}/></>}</>}
 {view==='history'&&<><div className="eye">ARCHIVIO</div><h1>Storico<br/><em>giornate.</em></h1>{!slips.length?<div className="empty">Nessuna schedina ancora.</div>:<div className="list">{slips.map(s=><button key={s.id} onClick={()=>{setChosen(s.id);setView('detail')}}><SlipCard slip={s}/></button>)}</div>}</>}
 {view==='detail'&&selected&&<><button className="back" onClick={()=>setView('history')}>← Storico</button><div className="eye">GIORNATA {selected.matchday} · {new Date(selected.date+'T12:00:00').toLocaleDateString('it-IT')}</div><h1>La tua<br/><em>multipla.</em></h1><SlipCard slip={selected}/><div className="picks">{selected.picks.map(p=>{const fair=100/p.probability,value=(p.odd*p.probability/100-1)*100;return <button className={`pick ${p.result}`} key={p.id} onClick={()=>cycle(selected,p.id)}><b>{symbols[p.result]}</b><span><strong>{p.match}</strong><small>{p.market} · quota {p.odd.toFixed(2)}</small><small>Equa {fair.toFixed(2)} · Value {value>=0?'+':''}{pct(value)} · {'●'.repeat(p.confidence)}{'○'.repeat(5-p.confidence)}</small></span><em>{labels[p.result]}</em></button>})}</div><p className="hint">Tocca una selezione per cambiarne l’esito.</p><div className="settle"><button onClick={()=>settle(selected,'lost')}>Multipla persa</button><button className="primary" onClick={()=>settle(selected,'won')}>Multipla vinta</button></div><button className="danger" onClick={()=>deleteSlip(selected)}>Elimina schedina</button></>}
 </section><button className="fab" onClick={()=>setModal('import')}>＋</button><nav><button className={view==='dash'?'active':''} onClick={()=>setView('dash')}><b>⌂</b>Dashboard</button><button className={view!=='dash'?'active':''} onClick={()=>setView('history')}><b>◷</b>Storico</button></nav>{msg&&<button className="toast" onClick={()=>setMsg('')}>{msg}</button>}
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className="modal"><button className="close" onClick={()=>setModal(null)}>×</button>{modal==='import'&&<><div className="eye">NUOVA GIORNATA</div><h2>Incolla la schedina</h2><p>Da 1 a 6 selezioni. Lo stake è sempre 3 €.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={EXAMPLE}/><button className="primary wide" onClick={importSlip}>Controlla e importa</button><button className="link" onClick={()=>setModal('schema')}>Vedi lo schema accettato</button></>}{modal==='schema'&&<><div className="eye">FORMATO ACCETTATO</div><h2>Schema JSON</h2><p><code>probability</code> è una percentuale; <code>confidence</code> va da 1 a 5.</p><pre>{EXAMPLE}</pre><button className="primary wide" onClick={()=>{navigator.clipboard.writeText(EXAMPLE);setMsg('Schema copiato.')}}>Copia esempio</button></>}{modal==='backup'&&<><div className="eye">I TUOI DATI</div><h2>Backup completo</h2><p>Esporta lo storico in un file JSON, oppure ripristinalo su un altro dispositivo.</p><button className="primary wide" onClick={backup}>Esporta backup</button><button className="secondary wide" onClick={()=>file.current?.click()}>Importa backup</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/><small className="privacy">🔒 Nessun dato lascia il dispositivo.</small></>}</div></div>}</main>}
function Title({title,meta,action}:{title:string;meta?:string;action?:()=>void}){return <div className="section-title"><h2>{title}</h2>{action?<button onClick={action}>Apri →</button>:<span>{meta}</span>}</div>}
function TrendChart({points}:{points:{day:number;value:number;result:R}[]}){if(!points.length)return <div className="chart-empty"><span>⌁</span><b>Il grafico nascerà qui</b><small>Segna l’esito della prima schedina.</small></div>;const values=[0,...points.map(p=>p.value)],min=Math.min(0,...values),max=Math.max(0,...values),range=max-min||6,toX=(i:number)=>34+i*(296/Math.max(1,points.length)),toY=(v:number)=>132-(v-min)/range*96,coords=[{x:34,y:toY(0)},...points.map((p,i)=>({x:toX(i+1),y:toY(p.value)}))],path=coords.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' '),zeroY=toY(0);return <div className="trend-card"><svg viewBox="0 0 360 166" role="img" aria-label="Profitto cumulativo per giornata"><title>Profitto cumulativo per giornata</title><line x1="34" y1={zeroY} x2="340" y2={zeroY} className="zero-line"/><text x="5" y="18" className="axis-label">{euro(max)}</text><text x="5" y="151" className="axis-label">{euro(min)}</text><path d={path} className={points.at(-1)!.value>=0?'trend-line positive-line':'trend-line negative-line'}/>{coords.slice(1).map((p,i)=><g key={points[i].day}><circle cx={p.x} cy={p.y} r="5" className={points[i].result==='won'?'point-win':'point-loss'}/><text x={p.x} y="157" textAnchor="middle" className="day-label">G{points[i].day}</text></g>)}</svg><div className="trend-value"><small>ORA</small><b className={points.at(-1)!.value>=0?'pos-text':'neg-text'}>{points.at(-1)!.value>=0?'+':''}{euro(points.at(-1)!.value)}</b></div></div>}
function OutcomeChart({slips}:{slips:Slip[]}){const items=slips.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.matchday-b.matchday),settled=items.filter(s=>s.result!=='pending'),max=Math.max(3,...settled.map(s=>Math.abs(s.returnAmount-3)));return <div className="outcome-card"><div className="outcome-grid">{items.map(s=>{const value=s.result==='pending'?null:s.returnAmount-3,height=value===null?6:Math.max(10,Math.abs(value)/max*44);return <div className="outcome-col" key={s.id} title={`Giornata ${s.matchday}: ${value===null?'in attesa':euro(value)}`}><div className="bar-zone"><i className={value===null?'pending-bar':value>=0?'gain-bar':'loss-bar'} style={value===null?{height:`${height}%`,top:'47%'}:value>=0?{height:`${height}%`,bottom:'50%'}:{height:`${height}%`,top:'50%'}}/></div><small>G{s.matchday}</small></div>})}</div><div className="zero-label">0 €</div></div>}
function Ring({value,label,detail}:{value:number;label:string;detail:string}){const safe=Math.max(0,Math.min(100,value));return <div className="ring-card"><div className="ring" style={{background:`conic-gradient(var(--green) ${safe}%, var(--ring-track) 0)`}}><span>{pct(value)}</span></div><div><small>WIN RATE</small><strong>{label}</strong><span>{detail}</span></div></div>}
function SlipCard({slip}:{slip:Slip}){const odd=slip.picks.reduce((a,p)=>a*p.odd,1);return <div className="slip"><span><b>GIORNATA {slip.matchday}</b><small>{slip.picks.length} selezioni · {new Date(slip.date+'T12:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short'})}</small></span><strong>@ {odd.toFixed(2)}</strong><em className={slip.result}>{labels[slip.result]}</em></div>}
