'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
type R='pending'|'won'|'lost'|'void';
type Pick={id:string;match:string;market:string;odd:number;probability:number;confidence:number;result:R};
type Slip={id:string;season:string;matchday:number;date:string;stake:3;result:R;returnAmount:number;notes?:string;picks:Pick[]};
const EXAMPLE=`{\n  "season": "2026/27",\n  "matchday": 1,\n  "date": "2026-08-23",\n  "notes": "Prima giornata",\n  "selections": [\n    {\n      "match": "Inter - Torino",\n      "market": "1",\n      "odd": 1.55,\n      "probability": 70,\n      "confidence": 4\n    }\n  ]\n}`;
const labels:Record<R,string>={pending:'In attesa',won:'Vinta',lost:'Persa',void:'Nulla'};
const symbols:Record<R,string>={pending:'—',won:'✓',lost:'×',void:'○'};
const euro=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
const pct=(n:number)=>`${n.toFixed(1).replace('.',',')}%`;
function db(){return new Promise<IDBDatabase>((ok,no)=>{const q=indexedDB.open('seriea-multipla',1);q.onupgradeneeded=()=>q.result.createObjectStore('slips',{keyPath:'id'});q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function readAll(){const d=await db();return new Promise<Slip[]>((ok,no)=>{const q=d.transaction('slips').objectStore('slips').getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function put(s:Slip){const d=await db();return new Promise<void>((ok,no)=>{const q=d.transaction('slips','readwrite').objectStore('slips').put(s);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)})}
async function replace(items:Slip[]){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('slips','readwrite'),s=t.objectStore('slips');s.clear();items.forEach(x=>s.put(x));t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
function parse(raw:unknown):Slip{if(!raw||typeof raw!=='object')throw Error('Il JSON deve contenere un oggetto.');const x=raw as Record<string,unknown>,a=x.selections;if(!Array.isArray(a)||a.length<1||a.length>6)throw Error('Servono da 1 a 6 selezioni.');const season=String(x.season||''),date=String(x.date||''),matchday=Number(x.matchday);if(!season||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isInteger(matchday)||matchday<1)throw Error('Controlla stagione, giornata e data.');const picks=a.map((v,i)=>{const z=v as Record<string,unknown>,odd=Number(z.odd),probability=Number(z.probability),confidence=Number(z.confidence);if(!z.match||!z.market||odd<=1||probability<=0||probability>100||confidence<1||confidence>5)throw Error(`Selezione ${i+1}: valori non validi.`);return{id:crypto.randomUUID(),match:String(z.match),market:String(z.market),odd,probability,confidence,result:'pending' as R}});return{id:`${season}-${matchday}-${date}`,season,matchday,date,stake:3,result:'pending',returnAmount:0,notes:String(x.notes||''),picks}}
export default function Home(){
 const[slips,setSlips]=useState<Slip[]>([]),[ready,setReady]=useState(false),[view,setView]=useState<'dash'|'history'|'detail'>('dash'),[chosen,setChosen]=useState(''),[modal,setModal]=useState<'import'|'schema'|'backup'|null>(null),[text,setText]=useState(''),[msg,setMsg]=useState('');const file=useRef<HTMLInputElement>(null);
 const load=async()=>{setSlips((await readAll()).sort((a,b)=>b.date.localeCompare(a.date)||b.matchday-a.matchday));setReady(true)};useEffect(()=>{readAll().then(data=>{setSlips(data.sort((a,b)=>b.date.localeCompare(a.date)||b.matchday-a.matchday));setReady(true)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')},[]);
 const selected=slips.find(x=>x.id===chosen)||slips[0];const stats=useMemo(()=>{const stake=slips.length*3,returns=slips.reduce((a,s)=>a+s.returnAmount,0),settled=slips.filter(s=>s.result!=='pending'),p=slips.flatMap(s=>s.picks).filter(x=>x.result==='won'||x.result==='lost');return{stake,returns,profit:returns-stake,roi:stake?(returns-stake)/stake*100:0,win:settled.length?settled.filter(s=>s.result==='won').length/settled.length*100:0,hit:p.length?p.filter(x=>x.result==='won').length/p.length*100:0}},[slips]);
 const save=async(s:Slip)=>{await put(s);await load()};const importSlip=async()=>{try{const s=parse(JSON.parse(text));await put(s);setText('');setModal(null);setMsg(`Giornata ${s.matchday} importata.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'JSON non valido.')}};
 const backup=()=>{const b=new Blob([JSON.stringify({app:'seriea-multipla',version:1,exportedAt:new Date().toISOString(),slips},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`seriea-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=async(f:File)=>{try{const x=JSON.parse(await f.text());if(x.app!=='seriea-multipla'||!Array.isArray(x.slips))throw Error('Backup non riconosciuto.');await replace(x.slips);await load();setMsg('Backup ripristinato.')}catch(e){setMsg(e instanceof Error?e.message:'Backup non valido.')}};
 const cycle=async(s:Slip,id:string)=>{const o:R[]=['pending','won','lost','void'];await save({...s,picks:s.picks.map(p=>p.id===id?{...p,result:o[(o.indexOf(p.result)+1)%4]}:p)})};const settle=async(s:Slip,r:R)=>{const odd=s.picks.reduce((a,p)=>a*p.odd,1);await save({...s,result:r,returnAmount:r==='won'?+(s.stake*odd).toFixed(2):r==='void'?3:0})};
 return <main className="shell"><header><div className="brand"><b>3</b><span><strong>La Multipla</strong><small>Serie A · stake fisso €3</small></span></div><button className="round" onClick={()=>setModal('backup')}>↥</button></header><section className="content">
 {view==='dash'&&<><div className="eye">PANORAMICA STAGIONE</div><h1>Il tuo campionato,<br/><em>una multipla alla volta.</em></h1>{!ready?<div className="empty">Caricamento…</div>:!slips.length?<div className="welcome"><div>⚽</div><h2>Pronto per la prima giornata?</h2><p>Importa il JSON della schedina. I dati restano solo su questo dispositivo.</p><button className="primary" onClick={()=>setModal('import')}>Importa schedina</button><button className="link" onClick={()=>setModal('schema')}>Vedi formato JSON</button></div>:<><div className="hero"><small>PROFIT / LOSS</small><strong className={stats.profit>=0?'pos':'neg'}>{stats.profit>=0?'+':''}{euro(stats.profit)}</strong><div>{[['ROI',pct(stats.roi)],['Ritorni',euro(stats.returns)],['Puntato',euro(stats.stake)]].map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}</div></div><div className="metrics"><span><small>Multiple vinte</small><strong>{pct(stats.win)}</strong></span><span><small>Hit rate selezioni</small><strong>{pct(stats.hit)}</strong></span></div><Title title="Andamento" meta={slips[0]?.season}/><div className="chart">{slips.slice().reverse().map((s,i)=>{const n=slips.slice().reverse().slice(0,i+1).reduce((a,x)=>a+x.returnAmount-3,0);return <span key={s.id}><i className={n>=0?'up':'down'} style={{height:`${Math.min(88,20+Math.abs(n)*8)}px`}}/><small>{s.matchday}</small></span>})}</div><Title title="Ultima schedina" action={()=>{setChosen(slips[0].id);setView('detail')}}/><SlipCard slip={slips[0]}/></>}</>}
 {view==='history'&&<><div className="eye">ARCHIVIO</div><h1>Storico<br/><em>giornate.</em></h1>{!slips.length?<div className="empty">Nessuna schedina ancora.</div>:<div className="list">{slips.map(s=><button key={s.id} onClick={()=>{setChosen(s.id);setView('detail')}}><SlipCard slip={s}/></button>)}</div>}</>}
 {view==='detail'&&selected&&<><button className="back" onClick={()=>setView('history')}>← Storico</button><div className="eye">GIORNATA {selected.matchday} · {new Date(selected.date+'T12:00:00').toLocaleDateString('it-IT')}</div><h1>La tua<br/><em>multipla.</em></h1><SlipCard slip={selected}/><div className="picks">{selected.picks.map(p=>{const fair=100/p.probability,value=(p.odd*p.probability/100-1)*100;return <button className={`pick ${p.result}`} key={p.id} onClick={()=>cycle(selected,p.id)}><b>{symbols[p.result]}</b><span><strong>{p.match}</strong><small>{p.market} · quota {p.odd.toFixed(2)}</small><small>Equa {fair.toFixed(2)} · Value {value>=0?'+':''}{pct(value)} · {'●'.repeat(p.confidence)}{'○'.repeat(5-p.confidence)}</small></span><em>{labels[p.result]}</em></button>})}</div><p className="hint">Tocca una selezione per cambiarne l’esito.</p><div className="settle"><button onClick={()=>settle(selected,'lost')}>Multipla persa</button><button className="primary" onClick={()=>settle(selected,'won')}>Multipla vinta</button></div></>}
 </section><button className="fab" onClick={()=>setModal('import')}>＋</button><nav><button className={view==='dash'?'active':''} onClick={()=>setView('dash')}><b>⌂</b>Dashboard</button><button className={view!=='dash'?'active':''} onClick={()=>setView('history')}><b>◷</b>Storico</button></nav>{msg&&<button className="toast" onClick={()=>setMsg('')}>{msg}</button>}
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className="modal"><button className="close" onClick={()=>setModal(null)}>×</button>{modal==='import'&&<><div className="eye">NUOVA GIORNATA</div><h2>Incolla la schedina</h2><p>Da 1 a 6 selezioni. Lo stake è sempre 3 €.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={EXAMPLE}/><button className="primary wide" onClick={importSlip}>Controlla e importa</button><button className="link" onClick={()=>setModal('schema')}>Vedi lo schema accettato</button></>}{modal==='schema'&&<><div className="eye">FORMATO ACCETTATO</div><h2>Schema JSON</h2><p><code>probability</code> è una percentuale; <code>confidence</code> va da 1 a 5.</p><pre>{EXAMPLE}</pre><button className="primary wide" onClick={()=>{navigator.clipboard.writeText(EXAMPLE);setMsg('Schema copiato.')}}>Copia esempio</button></>}{modal==='backup'&&<><div className="eye">I TUOI DATI</div><h2>Backup completo</h2><p>Esporta lo storico in un file JSON, oppure ripristinalo su un altro dispositivo.</p><button className="primary wide" onClick={backup}>Esporta backup</button><button className="secondary wide" onClick={()=>file.current?.click()}>Importa backup</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/><small className="privacy">🔒 Nessun dato lascia il dispositivo.</small></>}</div></div>}</main>}
function Title({title,meta,action}:{title:string;meta?:string;action?:()=>void}){return <div className="section-title"><h2>{title}</h2>{action?<button onClick={action}>Apri →</button>:<span>{meta}</span>}</div>}
function SlipCard({slip}:{slip:Slip}){const odd=slip.picks.reduce((a,p)=>a*p.odd,1);return <div className="slip"><span><b>GIORNATA {slip.matchday}</b><small>{slip.picks.length} selezioni · {new Date(slip.date+'T12:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short'})}</small></span><strong>@ {odd.toFixed(2)}</strong><em className={slip.result}>{labels[slip.result]}</em></div>}
